/*
 * scripts/build-browser.js
 * Bundle baselines.js + signals.js + verdict.js + analysis.js into a single
 * public/analysis.js so it can be loaded in a browser via <script src>.
 */
const fs = require('fs');
const path = require('path');

const root = path.resolve(__dirname, '..');
const read = (p) => fs.readFileSync(path.join(root, p), 'utf8');

const baselines = read('baselines.js');
const signals = read('signals.js');
const verdict = read('verdict.js');
const analysis = read('analysis.js');

const bundle =
`/* AUTO-GENERATED by scripts/build-browser.js — do not edit public/analysis.js directly.
   Re-run \`node scripts/build-browser.js\` after editing the Node-side modules. */
(function(){
  var modules = window.__atc_modules = window.__atc_modules || {};
  function req(name) {
    var m = modules[name];
    if (!m) throw new Error('atc bundle: missing module ' + name);
    return m.exports || m;
  }
  /* --- baselines --- */
  modules.baselines = modules.baselines || {};
  (function(module){
${baselines}
  })(modules.baselines);

  /* --- signals --- */
  modules.signals = modules.signals || {};
  (function(module){
${signals.replace(/require\('\.\/baselines'\)/g, "req('baselines')")}
  })(modules.signals);

  /* --- verdict --- */
  modules.verdict = modules.verdict || {};
  (function(module){
${verdict
  .replace(/require\('\.\/signals'\)/g, "req('signals')")
  .replace(/require\('\.\/baselines'\)/g, "req('baselines')")}
  })(modules.verdict);

  /* --- analysis (engine) --- */
  modules.analysis = modules.analysis || {};
  (function(module){
${analysis
  .replace(/require\('\.\/verdict'\)/g, "req('verdict')")
  .replace(/require\('\.\/baselines'\)/g, "req('baselines')")}
  })(modules.analysis);
})();
`;

const out = path.join(root, 'public', 'analysis.js');
fs.writeFileSync(out, bundle);
console.log('wrote', out, '(' + bundle.length + ' bytes)');
